# https://github.com/novoic/blabla/blob/master/FEATURES.md
blabla_features_list = [
    "num_pauses",
    "total_pause_time",
    "mean_pause_duration",
    "between_utterance_pause_duration",
    "hesitation_ratio",
    "speech_rate",
    "maximum_speech_rate",
    "total_phonation_time",
    # "standardized_phonation_time",
    "total_locution_time",
    "noun_rate",
    "verb_rate",
    "demonstrative_rate",
    "adjective_rate",
    "adposition_rate",
    "adverb_rate",
    "auxiliary_rate",
    "conjunction_rate",
    "determiner_rate",
    "interjection_rate",
    "numeral_rate",
    "particle_rate",
    "pronoun_rate",
    "proper_noun_rate",
    "subordinating_conjunction_rate",
    "possessive_rate",
    "noun_verb_ratio",
    "noun_ratio",
    "pronoun_noun_ratio",
    "closed_class_word_rate",
    "open_class_word_rate",
    # "total_dependency_distance",
    # "average_dependency_distance",
    # "total_dependencies",
    "content_density",
    "idea_density",
    "honore_statistic",
    "brunet_index",
    "type_token_ratio",
    "word_length",
    "prop_inflected_verbs",
    "prop_auxiliary_verbs",
    "prop_gerund_verbs",
    "prop_participles",
    "prop_nouns_with_det",
    "prop_nouns_with_adj",
]